JustinandKelley/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JustinandKelley.Models;

namespace JustinandKelley.Controllers
{ 
    public class FAQController : BaseController
    {
        private JustinandKelleyEntities db = new JustinandKelleyEntities();

        //
        // GET: /FAQ/

        public ViewResult Index()
        {
            return View(db.FAQs.ToList());
        }

        //
        // GET: /FAQ/Details/5

        public ViewResult Details(int id)
        {
            FAQ faq = db.FAQs.Single(f => f.ID == id);
            return View(faq);
        }

        //
        // GET: /FAQ/Create

        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /FAQ/Create

        [HttpPost]
        public ActionResult Create(FAQ faq)
        {
            if (ModelState.IsValid)
            {
                db.FAQs.AddObject(faq);
                db.SaveChanges();
                try
                {
                    SendQAEmail(faq);
                }
                catch
                {
                    //do nothing
                }
                return RedirectToAction("Index");  
            }

            return View(faq);
        }

        private void SendQAEmail(FAQ faq)
        {
            String subject = "New Wedding Question";
            string body = "Question: " + faq.Question;
            RSVPController.SendEmail(body, subject);
        }
        
        //
        // GET: /FAQ/Edit/5
 
        public ActionResult Edit(int id)
        {
            FAQ faq = db.FAQs.Single(f => f.ID == id);
            return View(faq);
        }

        //
        // POST: /FAQ/Edit/5

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult Edit(FAQ faq)
        {
            if (ModelState.IsValid)
            {
                db.FAQs.Attach(faq);
                db.ObjectStateManager.ChangeObjectState(faq, EntityState.Modified);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(faq);
        }

        //
        // GET: /FAQ/Delete/5
 
        public ActionResult Delete(int id)
        {
            FAQ faq = db.FAQs.Single(f => f.ID == id);
            return View(faq);
        }

        //
        // POST: /FAQ/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            FAQ faq = db.FAQs.Single(f => f.ID == id);
            db.FAQs.DeleteObject(faq);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

JustinandKelley/Views/Shared/_Layout.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link rel="stylesheet" type="text/css" href="@Url.Content("~/Content/themes/anoceanofsky/anoceanofsky.css")" />
<title>@ViewBag.Title</title>
</head>

<body>
    <div id="page">
    <header>
        <div class="topNavigationLink">@Html.ActionLink("Home", "Index", "Home")</div>
        <div class="topNavigationLink">@Html.ActionLink("Contact", "Contact", "Home")</div>
        <div class="topNavigationLink">@Html.ActionLink("RSVP", "Create", "RSVP")</div>
        <div class="topNavigationLink">@Html.ActionLink("Q&A", "Index", "FAQ")</div>
	</div>
    </header>
    <div id="mainPicture">
    	<div class="picture">
        	<div id="headerTitle">Justin and Kelley</div>
            <div id="headerSubtext"></div>
        </div>
    </div>
        <div class="contentBox">
    	<div class="innerBox">
        @RenderBody()
        	<!--<div class="contentTitle">The Title of an Article</div>
          <div class="contentText"><p>You may use this template on any site, anywhere, for free just please leave the link back to me in the footer.   This template validates XHTML Strict 1.0, CSS Validates as well; enjoy :) </p><br />
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Integer mi. Vivamus sit amet neque vitae sapien bibendum sodales. Curabitur elementum. Duis imperdiet. Donec eleifend porttitor sapien. Praesent leo. Quisque auctor velit sed tellus. Suspendisse potenti. Aenean laoreet imperdiet nunc. Donec commodo suscipit dolor. Aenean nibh. Sed id odio. Aliquam lobortis risus ut felis. Sed vehicula pellentesque quam.</p><br />
          <p>Vestibulum augue quam, interdum id, congue semper, convallis non, velit. Quisque augue tortor, tristique ac, scelerisque eget, aliquam id, sem. Aenean lorem. Fusce velit nibh, dapibus quis, laoreet nec, porta a, dui. Nullam ac urna. Proin eget elit. Nunc scelerisque venenatis urna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce congue, turpis ut commodo mattis, pede erat fringilla tellus, pulvinar suscipit odio lorem sed pede.</p></div>

        
        <div class="contentTitle">So Many Titles, So Little Time.</div>
            <div class="contentText"><p>You may use this template on any site, anywhere, for free just please leave the link back to me in the footer.   This template validates XHTML Strict 1.0, CSS Validates as well; enjoy :) </p><br />
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Integer mi. Vivamus sit amet neque vitae sapien bibendum sodales. Curabitur elementum. Duis imperdiet. Donec eleifend porttitor sapien. Praesent leo. Quisque auctor velit sed tellus. Suspendisse potenti. Aenean laoreet imperdiet nunc. Donec commodo suscipit dolor. Aenean nibh. Sed id odio. Aliquam lobortis risus ut felis. Sed vehicula pellentesque quam.</p><br />
          <p>Vestibulum augue quam, interdum id, congue semper, convallis non, velit. Quisque augue tortor, tristique ac, scelerisque eget, aliquam id, sem. Aenean lorem. Fusce velit nibh, dapibus quis, laoreet nec, porta a, dui. Nullam ac urna. Proin eget elit. Nunc scelerisque venenatis urna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce congue, turpis ut commodo mattis, pede erat fringilla tellus, pulvinar suscipit odio lorem sed pede.</p></div>
        
        
        <div class="contentTitle">Yet Another  One!</div>
          <div class="contentText"><p>You may use this template on any site, anywhere, for free just please leave the link back to me in the footer.   This template validates XHTML Strict 1.0, CSS Validates as well; enjoy :) </p><br />
        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Integer mi. Vivamus sit amet neque vitae sapien bibendum sodales. Curabitur elementum. Duis imperdiet. Donec eleifend porttitor sapien. Praesent leo. Quisque auctor velit sed tellus. Suspendisse potenti. Aenean laoreet imperdiet nunc. Donec commodo suscipit dolor. Aenean nibh. Sed id odio. Aliquam lobortis risus ut felis. Sed vehicula pellentesque quam.</p><br />
          <p>Vestibulum augue quam, interdum id, congue semper, convallis non, velit. Quisque augue tortor, tristique ac, scelerisque eget, aliquam id, sem. Aenean lorem. Fusce velit nibh, dapibus quis, laoreet nec, porta a, dui. Nullam ac urna. Proin eget elit. Nunc scelerisque venenatis urna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce congue, turpis ut commodo mattis, pede erat fringilla tellus, pulvinar suscipit odio lorem sed pede.</p></div>
        </div>
        -->
    </div>
    </div>
        <div id="footer"></div>
</body>
</html>

JustinandKelley/Views/Shared/_Layoutpar.cshtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>@ViewBag.Title</title>
<link href="@Url.Content("~/Content/themes/paradise-travel/styles.css")" rel="stylesheet" type="text/css" />
</head>

<body>
<!-- begin #container -->
<div id="container">
	<!-- begin #header -->
    <div id="header">
    	<div class="logo">
        	<em>Justin and Kelley</em>
        </div>
        <div id="navcontainer">
            <ul id="navlist">
                <li id="active"><a href="#">@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                <li>@Html.ActionLink("RSVP", "Index", "RSVP")</li>
            </ul>
        </div>
    </div>
    <!-- end #header -->
    <!-- begin #sidebar1 
    <div id="sidebar1">
    	<div class="sidebarTop"></div>
        <div class="sidebarCenter">
        	<h1>Free Web Templates</h1>
            <ul>
            	<li><a href="http://www.flash-templates-today.com">Free Flash Templates</a></li>
                <li><a href="http://www.facebookpagetemplates.com">Free Facebook Templates</a></li>
                <li><a href="http://www.templateholder.com">Free Web Templates</a></li>
                <li><a href="http://www.freeflashtemplate.net">Free Flash Templates</a></li>
                <li><a href="http://www.freecsstemplate.net">Free Css Templates</a></li>
            </ul>
            <br /><br />
            <h1>Last Company News</h1>
            <p>
            	We present to your attention our series of <a href="http://www.facebookpagetemplates.com">Free Facebook Templates</a>. Facebook FBML page templates is a good way to make your page attractive on facebook.<br /><br />Social Media have a big influence on all of us and our days it is not enough to have an attractive web site.<br /><br />
                If you want to be really successful then you need a strong page on Facebook. You can find here good quality facebook page templates that you can use to create your own page on facebook.
            </p>
            <br />
            <p>
            	FacebookPageTemplates.com offers you unique Facebook Page Templates absolutely for free.<br /><br />
                Our Facebook Pages are easy to install and can actually draw the attention of your page visitors. Owe to the unique design and the simple replacement of the content, our templates are very popular among facebook users.
            </p>
        </div>
        <div class="sidebarBottom"></div>
    </div>-->
    <!-- end #sidebar1 -->
    <!-- begin #mainContent -->
    <div id="mainContent">
    	@RenderBody()
    </div>
    <!-- end #mainContent -->
    <br class="clearfloat" />
    <!-- begin #footer -->
    <div id="footer">
    	<p>
        	Copyright &copy; 2010. Designed by <a href="http://www.facebookpagetemplates.com" title="Facebook Templates">Facebook Templates</a> |
            <a title="This page validates as XHTML 1.0 Strict" href="http://validator.w3.org/check/referer" class="footerLink"><abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a> | 
            <a title="This page validates as CSS" href="http://jigsaw.w3.org/css-validator/check/referer" class="footerLink"><abbr title="Cascading Style Sheets">CSS</abbr></a><br>
            <center><span style="width: 100%; font-family: helvetica; font-size: 10px;">Design Downloaded from <a href="http://www.template4all.com/css/" style="font-family: helvetica; color: gray; font-size: 11px;">Free CSS Templates</a> | <a href="http://www.freethemes4all.com" style="font-family: helvetica; color: gray; font-size: 11px;">Free Website Templates</a> | <a href="http://www.seodesign.us" style="font-family: helvetica; color: gray; font-size: 11px;">www.seodesign.us</a></span></center>
        </p>
    </div>   
</div>
<!-- end #footer -->
<!-- end #container -->
</body>
</html>

JustinandKelley/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}